DROP TABLE IF EXISTS `sys_user`;
CREATE TABLE `sys_user`  (
  `id` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `user_code` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '用户编码',
  `user_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '姓名',
  `user_pwd` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '密码',
  `sex` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '性别',
  `phone` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '电话',
  `email` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '邮箱',
  `user_type` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '角色类型',
  `duties` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '职务',
  `s_state` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `unit` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '组织名称',
  `unit_id` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '状态',
  `unit_code` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '组织编码',
  `postscript` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `station_code` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '场站编码',
  `update_time` datetime(0) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Dynamic;



DROP TABLE IF EXISTS `sys_org`;
CREATE TABLE `sys_org`  (
  `id` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `org_code` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '公司编码',
  `org_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '公司名称',
  `short_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '简称',
  `main_industry` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `org_type` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '公司类型',
  `parent_code` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '上级公司编码',
  `parent_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '上级公司名称',
  `org_path` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `org_country` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `s_state` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '公司状态',
  `sub_count` int(11) DEFAULT NULL,
  `l_level` int(11) DEFAULT NULL COMMENT '公司等级',
  `short_code` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `capacity` decimal(18, 2) DEFAULT NULL,
  `jt_code` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `sort` int(11) DEFAULT NULL,
  `is_normal` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '0：停运 1：运行',
  `installed_units` int(11) DEFAULT NULL,
  `reted_voltage` decimal(18, 2) DEFAULT NULL,
  `location` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '地址',
  `province` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '省份',
  `linkman` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '联系人',
  `telephone` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '联系电话',
  `coordinate_sys` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `longitude` decimal(18, 6) DEFAULT NULL,
  `latitude` decimal(18, 6) DEFAULT NULL,
  `assets_ratio` decimal(18, 2) DEFAULT NULL,
  `access_situation` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '接入情况(1 是 0 否)',
  `isalignment` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '是否统调(1 统调 0 非统调)',
  `is_production` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '是否投产',
  `equipment_capacity` decimal(18, 2) DEFAULT NULL,
  `design_capacity` decimal(18, 2) DEFAULT NULL,
  `is_increase` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `production_time` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '投产日期',
  `intro_image` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `intro_text` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `is_ts` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '技术监督组织机构区分，1：技术监督显示，2：技术监督不显示',
  `power_capacity` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `power_unit` int(11) DEFAULT NULL COMMENT '发电单元数量',
  `battery_manufacturer` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '电池组件厂家',
  `battery_type` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '（机组）电池类型',
  `support_form` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '（叶片直径）支架形式',
  `inverter_manufacture` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '（风机）逆变器厂家',
  `inverter_model` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '（风机）逆变器型号',
  `inverter_capacity` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `first_startup_time` datetime(0) DEFAULT NULL COMMENT '首台投产时间',
  `year_power` decimal(18, 2) DEFAULT NULL COMMENT '年设计值发电量',
  `year_user_hour` decimal(18, 2) DEFAULT NULL COMMENT '年利用小时设计值',
  `electricity_price` decimal(18, 2) DEFAULT NULL COMMENT '电价',
  `actual_capacity` decimal(18, 2) DEFAULT NULL COMMENT '实际容量',
  `full_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `simple_name` varchar(30) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `create_by` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '记录创建者',
  `create_by_name` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '创建者姓名',
  `create_at` datetime(0) DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '修改者账号',
  `update_by_name` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '修改者姓名',
  `update_at` datetime(0) DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Dynamic;


DROP TABLE IF EXISTS `sys_role`;
CREATE TABLE `sys_role`  (
  `role_id` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `role_code` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '角色编码',
  `role_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '角色名称',
  `role_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '描述',
  `update_user` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '更新者账号',
  `update_time` datetime(0) DEFAULT NULL COMMENT '更新时间',
  `s_state` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '状态',
  `root` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `l_level` int(11) DEFAULT NULL,
  `unit` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `department` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '部门',
  PRIMARY KEY (`role_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Compact;