package com.cpiinfo.sysmgt.entity;

public class Depart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department1.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department1.depart_name
     *
     * @mbg.generated
     */
    private String departName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department1.org_name
     *
     * @mbg.generated
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department1.org_code
     *
     * @mbg.generated
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department1.depart_status
     *
     * @mbg.generated
     */
    private String departStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department1.depart_code
     *
     * @mbg.generated
     */
    private String departCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department1.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    private String parentName;

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department1.principal
     *
     * @mbg.generated
     */
    private String principal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department1.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department1.postscript
     *
     * @mbg.generated
     */
    private String postscript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department1.id
     *
     * @return the value of sys_department1.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department1.id
     *
     * @param id the value for sys_department1.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department1.depart_name
     *
     * @return the value of sys_department1.depart_name
     *
     * @mbg.generated
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department1.depart_name
     *
     * @param departName the value for sys_department1.depart_name
     *
     * @mbg.generated
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department1.org_name
     *
     * @return the value of sys_department1.org_name
     *
     * @mbg.generated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department1.org_name
     *
     * @param orgName the value for sys_department1.org_name
     *
     * @mbg.generated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department1.org_code
     *
     * @return the value of sys_department1.org_code
     *
     * @mbg.generated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department1.org_code
     *
     * @param orgCode the value for sys_department1.org_code
     *
     * @mbg.generated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department1.depart_status
     *
     * @return the value of sys_department1.depart_status
     *
     * @mbg.generated
     */
    public String getDepartStatus() {
        return departStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department1.depart_status
     *
     * @param departStatus the value for sys_department1.depart_status
     *
     * @mbg.generated
     */
    public void setDepartStatus(String departStatus) {
        this.departStatus = departStatus == null ? null : departStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department1.depart_code
     *
     * @return the value of sys_department1.depart_code
     *
     * @mbg.generated
     */
    public String getDepartCode() {
        return departCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department1.depart_code
     *
     * @param departCode the value for sys_department1.depart_code
     *
     * @mbg.generated
     */
    public void setDepartCode(String departCode) {
        this.departCode = departCode == null ? null : departCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department1.parent_id
     *
     * @return the value of sys_department1.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department1.parent_id
     *
     * @param parentId the value for sys_department1.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department1.principal
     *
     * @return the value of sys_department1.principal
     *
     * @mbg.generated
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department1.principal
     *
     * @param principal the value for sys_department1.principal
     *
     * @mbg.generated
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department1.phone
     *
     * @return the value of sys_department1.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department1.phone
     *
     * @param phone the value for sys_department1.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department1.postscript
     *
     * @return the value of sys_department1.postscript
     *
     * @mbg.generated
     */
    public String getPostscript() {
        return postscript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department1.postscript
     *
     * @param postscript the value for sys_department1.postscript
     *
     * @mbg.generated
     */
    public void setPostscript(String postscript) {
        this.postscript = postscript == null ? null : postscript.trim();
    }
}