package com.cpiinfo.sysmgt.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_code
     *
     * @mbg.generated
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_name
     *
     * @mbg.generated
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.short_name
     *
     * @mbg.generated
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.main_industry
     *
     * @mbg.generated
     */
    private String mainIndustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_type
     *
     * @mbg.generated
     */
    private String orgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.parent_code
     *
     * @mbg.generated
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.parent_name
     *
     * @mbg.generated
     */
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_path
     *
     * @mbg.generated
     */
    private String orgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_country
     *
     * @mbg.generated
     */
    private String orgCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.s_state
     *
     * @mbg.generated
     */
    private String sState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.sub_count
     *
     * @mbg.generated
     */
    private Integer subCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.l_level
     *
     * @mbg.generated
     */
    private Integer lLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.short_code
     *
     * @mbg.generated
     */
    private String shortCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.capacity
     *
     * @mbg.generated
     */
    private BigDecimal capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.jt_code
     *
     * @mbg.generated
     */
    private String jtCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.is_normal
     *
     * @mbg.generated
     */
    private String isNormal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.installed_units
     *
     * @mbg.generated
     */
    private Integer installedUnits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.reted_voltage
     *
     * @mbg.generated
     */
    private BigDecimal retedVoltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.linkman
     *
     * @mbg.generated
     */
    private String linkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.coordinate_sys
     *
     * @mbg.generated
     */
    private String coordinateSys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.longitude
     *
     * @mbg.generated
     */
    private BigDecimal longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.latitude
     *
     * @mbg.generated
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.assets_ratio
     *
     * @mbg.generated
     */
    private BigDecimal assetsRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.access_situation
     *
     * @mbg.generated
     */
    private String accessSituation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.isalignment
     *
     * @mbg.generated
     */
    private String isalignment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.is_production
     *
     * @mbg.generated
     */
    private String isProduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.equipment_capacity
     *
     * @mbg.generated
     */
    private BigDecimal equipmentCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.design_capacity
     *
     * @mbg.generated
     */
    private BigDecimal designCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.is_increase
     *
     * @mbg.generated
     */
    private String isIncrease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.production_time
     *
     * @mbg.generated
     */
    private String productionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.intro_image
     *
     * @mbg.generated
     */
    private String introImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.intro_text
     *
     * @mbg.generated
     */
    private String introText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.is_ts
     *
     * @mbg.generated
     */
    private String isTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.power_capacity
     *
     * @mbg.generated
     */
    private String powerCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.power_unit
     *
     * @mbg.generated
     */
    private Integer powerUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.battery_manufacturer
     *
     * @mbg.generated
     */
    private String batteryManufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.battery_type
     *
     * @mbg.generated
     */
    private String batteryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.support_form
     *
     * @mbg.generated
     */
    private String supportForm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.inverter_manufacture
     *
     * @mbg.generated
     */
    private String inverterManufacture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.inverter_model
     *
     * @mbg.generated
     */
    private String inverterModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.inverter_capacity
     *
     * @mbg.generated
     */
    private String inverterCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.first_startup_time
     *
     * @mbg.generated
     */
    private Date firstStartupTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.year_power
     *
     * @mbg.generated
     */
    private BigDecimal yearPower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.year_user_hour
     *
     * @mbg.generated
     */
    private BigDecimal yearUserHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.electricity_price
     *
     * @mbg.generated
     */
    private BigDecimal electricityPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.actual_capacity
     *
     * @mbg.generated
     */
    private BigDecimal actualCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.full_name
     *
     * @mbg.generated
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.simple_name
     *
     * @mbg.generated
     */
    private String simpleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.create_by_name
     *
     * @mbg.generated
     */
    private String createByName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.update_by_name
     *
     * @mbg.generated
     */
    private String updateByName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.registered_capital
     *
     * @mbg.generated
     */
    private String registeredCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.legal_representative
     *
     * @mbg.generated
     */
    private String legalRepresentative;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.establish_time
     *
     * @mbg.generated
     */
    private Date establishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.id
     *
     * @return the value of sys_org.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.id
     *
     * @param id the value for sys_org.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_code
     *
     * @return the value of sys_org.org_code
     *
     * @mbg.generated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_code
     *
     * @param orgCode the value for sys_org.org_code
     *
     * @mbg.generated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_name
     *
     * @return the value of sys_org.org_name
     *
     * @mbg.generated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_name
     *
     * @param orgName the value for sys_org.org_name
     *
     * @mbg.generated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.short_name
     *
     * @return the value of sys_org.short_name
     *
     * @mbg.generated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.short_name
     *
     * @param shortName the value for sys_org.short_name
     *
     * @mbg.generated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.main_industry
     *
     * @return the value of sys_org.main_industry
     *
     * @mbg.generated
     */
    public String getMainIndustry() {
        return mainIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.main_industry
     *
     * @param mainIndustry the value for sys_org.main_industry
     *
     * @mbg.generated
     */
    public void setMainIndustry(String mainIndustry) {
        this.mainIndustry = mainIndustry == null ? null : mainIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_type
     *
     * @return the value of sys_org.org_type
     *
     * @mbg.generated
     */
    public String getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_type
     *
     * @param orgType the value for sys_org.org_type
     *
     * @mbg.generated
     */
    public void setOrgType(String orgType) {
        this.orgType = orgType == null ? null : orgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.parent_code
     *
     * @return the value of sys_org.parent_code
     *
     * @mbg.generated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.parent_code
     *
     * @param parentCode the value for sys_org.parent_code
     *
     * @mbg.generated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.parent_name
     *
     * @return the value of sys_org.parent_name
     *
     * @mbg.generated
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.parent_name
     *
     * @param parentName the value for sys_org.parent_name
     *
     * @mbg.generated
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_path
     *
     * @return the value of sys_org.org_path
     *
     * @mbg.generated
     */
    public String getOrgPath() {
        return orgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_path
     *
     * @param orgPath the value for sys_org.org_path
     *
     * @mbg.generated
     */
    public void setOrgPath(String orgPath) {
        this.orgPath = orgPath == null ? null : orgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_country
     *
     * @return the value of sys_org.org_country
     *
     * @mbg.generated
     */
    public String getOrgCountry() {
        return orgCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_country
     *
     * @param orgCountry the value for sys_org.org_country
     *
     * @mbg.generated
     */
    public void setOrgCountry(String orgCountry) {
        this.orgCountry = orgCountry == null ? null : orgCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.s_state
     *
     * @return the value of sys_org.s_state
     *
     * @mbg.generated
     */
    public String getsState() {
        return sState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.s_state
     *
     * @param sState the value for sys_org.s_state
     *
     * @mbg.generated
     */
    public void setsState(String sState) {
        this.sState = sState == null ? null : sState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.sub_count
     *
     * @return the value of sys_org.sub_count
     *
     * @mbg.generated
     */
    public Integer getSubCount() {
        return subCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.sub_count
     *
     * @param subCount the value for sys_org.sub_count
     *
     * @mbg.generated
     */
    public void setSubCount(Integer subCount) {
        this.subCount = subCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.l_level
     *
     * @return the value of sys_org.l_level
     *
     * @mbg.generated
     */
    public Integer getlLevel() {
        return lLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.l_level
     *
     * @param lLevel the value for sys_org.l_level
     *
     * @mbg.generated
     */
    public void setlLevel(Integer lLevel) {
        this.lLevel = lLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.short_code
     *
     * @return the value of sys_org.short_code
     *
     * @mbg.generated
     */
    public String getShortCode() {
        return shortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.short_code
     *
     * @param shortCode the value for sys_org.short_code
     *
     * @mbg.generated
     */
    public void setShortCode(String shortCode) {
        this.shortCode = shortCode == null ? null : shortCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.capacity
     *
     * @return the value of sys_org.capacity
     *
     * @mbg.generated
     */
    public BigDecimal getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.capacity
     *
     * @param capacity the value for sys_org.capacity
     *
     * @mbg.generated
     */
    public void setCapacity(BigDecimal capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.jt_code
     *
     * @return the value of sys_org.jt_code
     *
     * @mbg.generated
     */
    public String getJtCode() {
        return jtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.jt_code
     *
     * @param jtCode the value for sys_org.jt_code
     *
     * @mbg.generated
     */
    public void setJtCode(String jtCode) {
        this.jtCode = jtCode == null ? null : jtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.sort
     *
     * @return the value of sys_org.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.sort
     *
     * @param sort the value for sys_org.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.is_normal
     *
     * @return the value of sys_org.is_normal
     *
     * @mbg.generated
     */
    public String getIsNormal() {
        return isNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.is_normal
     *
     * @param isNormal the value for sys_org.is_normal
     *
     * @mbg.generated
     */
    public void setIsNormal(String isNormal) {
        this.isNormal = isNormal == null ? null : isNormal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.installed_units
     *
     * @return the value of sys_org.installed_units
     *
     * @mbg.generated
     */
    public Integer getInstalledUnits() {
        return installedUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.installed_units
     *
     * @param installedUnits the value for sys_org.installed_units
     *
     * @mbg.generated
     */
    public void setInstalledUnits(Integer installedUnits) {
        this.installedUnits = installedUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.reted_voltage
     *
     * @return the value of sys_org.reted_voltage
     *
     * @mbg.generated
     */
    public BigDecimal getRetedVoltage() {
        return retedVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.reted_voltage
     *
     * @param retedVoltage the value for sys_org.reted_voltage
     *
     * @mbg.generated
     */
    public void setRetedVoltage(BigDecimal retedVoltage) {
        this.retedVoltage = retedVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.location
     *
     * @return the value of sys_org.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.location
     *
     * @param location the value for sys_org.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.province
     *
     * @return the value of sys_org.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.province
     *
     * @param province the value for sys_org.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.linkman
     *
     * @return the value of sys_org.linkman
     *
     * @mbg.generated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.linkman
     *
     * @param linkman the value for sys_org.linkman
     *
     * @mbg.generated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.telephone
     *
     * @return the value of sys_org.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.telephone
     *
     * @param telephone the value for sys_org.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.coordinate_sys
     *
     * @return the value of sys_org.coordinate_sys
     *
     * @mbg.generated
     */
    public String getCoordinateSys() {
        return coordinateSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.coordinate_sys
     *
     * @param coordinateSys the value for sys_org.coordinate_sys
     *
     * @mbg.generated
     */
    public void setCoordinateSys(String coordinateSys) {
        this.coordinateSys = coordinateSys == null ? null : coordinateSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.longitude
     *
     * @return the value of sys_org.longitude
     *
     * @mbg.generated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.longitude
     *
     * @param longitude the value for sys_org.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.latitude
     *
     * @return the value of sys_org.latitude
     *
     * @mbg.generated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.latitude
     *
     * @param latitude the value for sys_org.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.assets_ratio
     *
     * @return the value of sys_org.assets_ratio
     *
     * @mbg.generated
     */
    public BigDecimal getAssetsRatio() {
        return assetsRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.assets_ratio
     *
     * @param assetsRatio the value for sys_org.assets_ratio
     *
     * @mbg.generated
     */
    public void setAssetsRatio(BigDecimal assetsRatio) {
        this.assetsRatio = assetsRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.access_situation
     *
     * @return the value of sys_org.access_situation
     *
     * @mbg.generated
     */
    public String getAccessSituation() {
        return accessSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.access_situation
     *
     * @param accessSituation the value for sys_org.access_situation
     *
     * @mbg.generated
     */
    public void setAccessSituation(String accessSituation) {
        this.accessSituation = accessSituation == null ? null : accessSituation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.isalignment
     *
     * @return the value of sys_org.isalignment
     *
     * @mbg.generated
     */
    public String getIsalignment() {
        return isalignment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.isalignment
     *
     * @param isalignment the value for sys_org.isalignment
     *
     * @mbg.generated
     */
    public void setIsalignment(String isalignment) {
        this.isalignment = isalignment == null ? null : isalignment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.is_production
     *
     * @return the value of sys_org.is_production
     *
     * @mbg.generated
     */
    public String getIsProduction() {
        return isProduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.is_production
     *
     * @param isProduction the value for sys_org.is_production
     *
     * @mbg.generated
     */
    public void setIsProduction(String isProduction) {
        this.isProduction = isProduction == null ? null : isProduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.equipment_capacity
     *
     * @return the value of sys_org.equipment_capacity
     *
     * @mbg.generated
     */
    public BigDecimal getEquipmentCapacity() {
        return equipmentCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.equipment_capacity
     *
     * @param equipmentCapacity the value for sys_org.equipment_capacity
     *
     * @mbg.generated
     */
    public void setEquipmentCapacity(BigDecimal equipmentCapacity) {
        this.equipmentCapacity = equipmentCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.design_capacity
     *
     * @return the value of sys_org.design_capacity
     *
     * @mbg.generated
     */
    public BigDecimal getDesignCapacity() {
        return designCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.design_capacity
     *
     * @param designCapacity the value for sys_org.design_capacity
     *
     * @mbg.generated
     */
    public void setDesignCapacity(BigDecimal designCapacity) {
        this.designCapacity = designCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.is_increase
     *
     * @return the value of sys_org.is_increase
     *
     * @mbg.generated
     */
    public String getIsIncrease() {
        return isIncrease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.is_increase
     *
     * @param isIncrease the value for sys_org.is_increase
     *
     * @mbg.generated
     */
    public void setIsIncrease(String isIncrease) {
        this.isIncrease = isIncrease == null ? null : isIncrease.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.production_time
     *
     * @return the value of sys_org.production_time
     *
     * @mbg.generated
     */
    public String getProductionTime() {
        return productionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.production_time
     *
     * @param productionTime the value for sys_org.production_time
     *
     * @mbg.generated
     */
    public void setProductionTime(String productionTime) {
        this.productionTime = productionTime == null ? null : productionTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.intro_image
     *
     * @return the value of sys_org.intro_image
     *
     * @mbg.generated
     */
    public String getIntroImage() {
        return introImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.intro_image
     *
     * @param introImage the value for sys_org.intro_image
     *
     * @mbg.generated
     */
    public void setIntroImage(String introImage) {
        this.introImage = introImage == null ? null : introImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.intro_text
     *
     * @return the value of sys_org.intro_text
     *
     * @mbg.generated
     */
    public String getIntroText() {
        return introText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.intro_text
     *
     * @param introText the value for sys_org.intro_text
     *
     * @mbg.generated
     */
    public void setIntroText(String introText) {
        this.introText = introText == null ? null : introText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.is_ts
     *
     * @return the value of sys_org.is_ts
     *
     * @mbg.generated
     */
    public String getIsTs() {
        return isTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.is_ts
     *
     * @param isTs the value for sys_org.is_ts
     *
     * @mbg.generated
     */
    public void setIsTs(String isTs) {
        this.isTs = isTs == null ? null : isTs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.power_capacity
     *
     * @return the value of sys_org.power_capacity
     *
     * @mbg.generated
     */
    public String getPowerCapacity() {
        return powerCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.power_capacity
     *
     * @param powerCapacity the value for sys_org.power_capacity
     *
     * @mbg.generated
     */
    public void setPowerCapacity(String powerCapacity) {
        this.powerCapacity = powerCapacity == null ? null : powerCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.power_unit
     *
     * @return the value of sys_org.power_unit
     *
     * @mbg.generated
     */
    public Integer getPowerUnit() {
        return powerUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.power_unit
     *
     * @param powerUnit the value for sys_org.power_unit
     *
     * @mbg.generated
     */
    public void setPowerUnit(Integer powerUnit) {
        this.powerUnit = powerUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.battery_manufacturer
     *
     * @return the value of sys_org.battery_manufacturer
     *
     * @mbg.generated
     */
    public String getBatteryManufacturer() {
        return batteryManufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.battery_manufacturer
     *
     * @param batteryManufacturer the value for sys_org.battery_manufacturer
     *
     * @mbg.generated
     */
    public void setBatteryManufacturer(String batteryManufacturer) {
        this.batteryManufacturer = batteryManufacturer == null ? null : batteryManufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.battery_type
     *
     * @return the value of sys_org.battery_type
     *
     * @mbg.generated
     */
    public String getBatteryType() {
        return batteryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.battery_type
     *
     * @param batteryType the value for sys_org.battery_type
     *
     * @mbg.generated
     */
    public void setBatteryType(String batteryType) {
        this.batteryType = batteryType == null ? null : batteryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.support_form
     *
     * @return the value of sys_org.support_form
     *
     * @mbg.generated
     */
    public String getSupportForm() {
        return supportForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.support_form
     *
     * @param supportForm the value for sys_org.support_form
     *
     * @mbg.generated
     */
    public void setSupportForm(String supportForm) {
        this.supportForm = supportForm == null ? null : supportForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.inverter_manufacture
     *
     * @return the value of sys_org.inverter_manufacture
     *
     * @mbg.generated
     */
    public String getInverterManufacture() {
        return inverterManufacture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.inverter_manufacture
     *
     * @param inverterManufacture the value for sys_org.inverter_manufacture
     *
     * @mbg.generated
     */
    public void setInverterManufacture(String inverterManufacture) {
        this.inverterManufacture = inverterManufacture == null ? null : inverterManufacture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.inverter_model
     *
     * @return the value of sys_org.inverter_model
     *
     * @mbg.generated
     */
    public String getInverterModel() {
        return inverterModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.inverter_model
     *
     * @param inverterModel the value for sys_org.inverter_model
     *
     * @mbg.generated
     */
    public void setInverterModel(String inverterModel) {
        this.inverterModel = inverterModel == null ? null : inverterModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.inverter_capacity
     *
     * @return the value of sys_org.inverter_capacity
     *
     * @mbg.generated
     */
    public String getInverterCapacity() {
        return inverterCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.inverter_capacity
     *
     * @param inverterCapacity the value for sys_org.inverter_capacity
     *
     * @mbg.generated
     */
    public void setInverterCapacity(String inverterCapacity) {
        this.inverterCapacity = inverterCapacity == null ? null : inverterCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.first_startup_time
     *
     * @return the value of sys_org.first_startup_time
     *
     * @mbg.generated
     */
    public Date getFirstStartupTime() {
        return firstStartupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.first_startup_time
     *
     * @param firstStartupTime the value for sys_org.first_startup_time
     *
     * @mbg.generated
     */
    public void setFirstStartupTime(Date firstStartupTime) {
        this.firstStartupTime = firstStartupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.year_power
     *
     * @return the value of sys_org.year_power
     *
     * @mbg.generated
     */
    public BigDecimal getYearPower() {
        return yearPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.year_power
     *
     * @param yearPower the value for sys_org.year_power
     *
     * @mbg.generated
     */
    public void setYearPower(BigDecimal yearPower) {
        this.yearPower = yearPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.year_user_hour
     *
     * @return the value of sys_org.year_user_hour
     *
     * @mbg.generated
     */
    public BigDecimal getYearUserHour() {
        return yearUserHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.year_user_hour
     *
     * @param yearUserHour the value for sys_org.year_user_hour
     *
     * @mbg.generated
     */
    public void setYearUserHour(BigDecimal yearUserHour) {
        this.yearUserHour = yearUserHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.electricity_price
     *
     * @return the value of sys_org.electricity_price
     *
     * @mbg.generated
     */
    public BigDecimal getElectricityPrice() {
        return electricityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.electricity_price
     *
     * @param electricityPrice the value for sys_org.electricity_price
     *
     * @mbg.generated
     */
    public void setElectricityPrice(BigDecimal electricityPrice) {
        this.electricityPrice = electricityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.actual_capacity
     *
     * @return the value of sys_org.actual_capacity
     *
     * @mbg.generated
     */
    public BigDecimal getActualCapacity() {
        return actualCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.actual_capacity
     *
     * @param actualCapacity the value for sys_org.actual_capacity
     *
     * @mbg.generated
     */
    public void setActualCapacity(BigDecimal actualCapacity) {
        this.actualCapacity = actualCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.full_name
     *
     * @return the value of sys_org.full_name
     *
     * @mbg.generated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.full_name
     *
     * @param fullName the value for sys_org.full_name
     *
     * @mbg.generated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.simple_name
     *
     * @return the value of sys_org.simple_name
     *
     * @mbg.generated
     */
    public String getSimpleName() {
        return simpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.simple_name
     *
     * @param simpleName the value for sys_org.simple_name
     *
     * @mbg.generated
     */
    public void setSimpleName(String simpleName) {
        this.simpleName = simpleName == null ? null : simpleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.create_by
     *
     * @return the value of sys_org.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.create_by
     *
     * @param createBy the value for sys_org.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.create_by_name
     *
     * @return the value of sys_org.create_by_name
     *
     * @mbg.generated
     */
    public String getCreateByName() {
        return createByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.create_by_name
     *
     * @param createByName the value for sys_org.create_by_name
     *
     * @mbg.generated
     */
    public void setCreateByName(String createByName) {
        this.createByName = createByName == null ? null : createByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.create_at
     *
     * @return the value of sys_org.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.create_at
     *
     * @param createAt the value for sys_org.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.update_by
     *
     * @return the value of sys_org.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.update_by
     *
     * @param updateBy the value for sys_org.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.update_by_name
     *
     * @return the value of sys_org.update_by_name
     *
     * @mbg.generated
     */
    public String getUpdateByName() {
        return updateByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.update_by_name
     *
     * @param updateByName the value for sys_org.update_by_name
     *
     * @mbg.generated
     */
    public void setUpdateByName(String updateByName) {
        this.updateByName = updateByName == null ? null : updateByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.update_at
     *
     * @return the value of sys_org.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.update_at
     *
     * @param updateAt the value for sys_org.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.registered_capital
     *
     * @return the value of sys_org.registered_capital
     *
     * @mbg.generated
     */
    public String getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.registered_capital
     *
     * @param registeredCapital the value for sys_org.registered_capital
     *
     * @mbg.generated
     */
    public void setRegisteredCapital(String registeredCapital) {
        this.registeredCapital = registeredCapital == null ? null : registeredCapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.legal_representative
     *
     * @return the value of sys_org.legal_representative
     *
     * @mbg.generated
     */
    public String getLegalRepresentative() {
        return legalRepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.legal_representative
     *
     * @param legalRepresentative the value for sys_org.legal_representative
     *
     * @mbg.generated
     */
    public void setLegalRepresentative(String legalRepresentative) {
        this.legalRepresentative = legalRepresentative == null ? null : legalRepresentative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.establish_time
     *
     * @return the value of sys_org.establish_time
     *
     * @mbg.generated
     */
    public Date getEstablishTime() {
        return establishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.establish_time
     *
     * @param establishTime the value for sys_org.establish_time
     *
     * @mbg.generated
     */
    public void setEstablishTime(Date establishTime) {
        this.establishTime = establishTime;
    }
}